### ISSUE TITLE
The way `CumulusLogger.createMessage` calls `str.format` prevents log/exception messages from containing curly braces if no args/kwargs are given

### ISSUE THREAD

**Issue by michaeljb** [nasa/cumulus-message-adapter-python#38]
Sometimes we want our lambda to log messages that include a JSON string, but provide a little context, such as `'Post to CMR response: <JSON here>'`. Unfortunately, that causes an error if passed as a string to `logger.debug` (and the other functions) or is included in the error message, due to this line:

https://github.com/nasa/cumulus-message-adapter-python/blob/v1.2.1/cumulus_logger.py#L213

That is, this code leads to a `KeyError: '"easter_bunny"'`:

```
from cumulus_logger import CumulusLogger
logger = CumulusLogger()
response_txt = '{"easter_bunny": "fake sample response"}'
logger.debug(f'POST to CMR response: {response_txt}')
```

And this code leads to an `IndexError: Replacement index 0 out of range for positional args tuple`:

```
logger.debug('POST to CMR response: {}')
```

When we first encountered this and I tracked down the `.format()` call on the LOC I linked above, I realized I could work around this issue with this code change:

```
# # broken version from above
# response_txt = '{"easter_bunny": "fake sample response"}'
# logger.debug(f'POST to CMR response: {response_txt}')

# workaround, send the JSON string to str.format's **kwargs
logger.debug('POST to CMR response: {response}', response=response_text)
```

However, this did not fully eliminate the `KeyErrors`; in the case where the CMR request failed, we raise an Exception so that the lambda fails appropriately:

```
if not response.ok:
    raise RuntimeError('Post to CMR Failed:', response.text)
```

And when cumulus-message-adapter-python tries to log the exception object at...

https://github.com/nasa/cumulus-message-adapter-python/blob/v1.2.1/run_cumulus_task.py#L68

...the exception gets converted to a string, `.format()` is called, and once again any curly braces in the message lead to a `KeyError` or `IndexError`.

I want to be able to have curly brace characters in my strings passed to the logger without an error being raised. #39 accomplishes this while maintaining the `.format()` functionality by skipping the `.format()` call if no args or kwargs are given.

**Comment by michaeljb** [comment]
REPL output demonstrating this:

```
[0] (01) 2021-11-03 17:18:54 mbrandt@cu-vpn-nsidc-172
  ~/projects/cumulus/cumulus-message-adapter-python (master %=)
  (cumulus-message-adapter-python-6Tqrlx0k) > python
Python 3.9.7 (default, Sep 17 2021, 13:07:12)
[Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from cumulus_logger import CumulusLogger
>>> logger = CumulusLogger()
>>> logger.createMessage("simple test {}")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mbrandt/projects/cumulus/cumulus-message-adapter-python/cumulus_logger.py", line 213, in createMessage
    fmt_message = str(message).format(*args, **kwargs)
IndexError: Replacement index 0 out of range for positional args tuple
>>> logger.createMessage("simple {test}")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mbrandt/projects/cumulus/cumulus-message-adapter-python/cumulus_logger.py", line 213, in createMessage
    fmt_message = str(message).format(*args, **kwargs)
KeyError: 'test'
>>> logger.createMessage('I want to log some JSON {"foo": "bar"}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mbrandt/projects/cumulus/cumulus-message-adapter-python/cumulus_logger.py", line 213, in createMessage
    fmt_message = str(message).format(*args, **kwargs)
KeyError: '"foo"'
```
